# Backend-only configuration for deployment on private machine
# This runs only the Django backend on private network
services:
  backend:
    image: ghcr.io/ccorbett0116/rotationalesc-website/backend:latest
    container_name: rotational-backend
    # Only expose to private network - no public ports
    expose:
      - "8000"
    volumes:
      - ./database:/app/database
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    env_file:
      - .env.backend
    restart: unless-stopped
    # Run database migrations on startup
    command: ["/app/entrypoint.sh"]

networks:
  default:
    driver: bridge