# Frontend-only configuration for deployment on public-facing machine
# This runs only the nginx frontend that proxies API calls to backend
services:
  frontend:
    image: ghcr.io/ccorbett0116/rotationalesc-website/frontend:latest
    container_name: rotational-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot:ro
    env_file:
      - .env.frontend
    restart: unless-stopped

  certbot:
    image: ghcr.io/ccorbett0116/rotationales-certbot:latest
    container_name: rotational-certbot
    volumes:
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env.frontend
    entrypoint: ""
    command: ["/bin/sh", "/custom-entrypoint.sh"]
    restart: unless-stopped
    depends_on:
      - frontend

networks:
  default:
    driver: bridge