# Generated by Django 5.2.6 on 2025-09-10 23:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
        model_name="order",
        name="confirmation_token",
        field=models.CharField(max_length=255, null=True, blank=True),
        )

    ]
