# Generated by Django 5.2.6 on 2025-09-11 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_populate_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="confirmation_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
