# Generated by Django 5.2.6 on 2025-09-20 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Pumps', 'Mechanical Seals')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'pumps', 'mechanical-seals')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Page description text')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (optional)', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (optional)', max_length=300)),
                ('active', models.BooleanField(default=True, help_text='Whether this category is active and accessible')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['equipment_category__order', 'label']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
        migrations.AddField(
            model_name='section',
            name='equipment_category',
            field=models.ForeignKey(blank=True, help_text='Which equipment category this section belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='products.equipmentcategory'),
        ),
    ]
