# Generated by Django 5.2.6 on 2025-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.CharField(choices=[('seals', 'Seals'), ('packing', 'Packing'), ('pumps', 'Pumps'), ('general', 'General Shop')], default='general', help_text='Which page should this product appear on', max_length=20),
        ),
    ]
