# Generated by Django 5.2.6 on 2025-09-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['page', 'label']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='page',
        ),
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('seals', 'Seals'), ('packing', 'Packing'), ('pumps', 'Pumps'), ('general', 'General Shop')], default='general', help_text='Which page should this section appear on', max_length=20),
        ),
    ]
