# Generated by Django 5.2.6 on 2025-09-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_change_product_id_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(help_text="Manufacturer's website URL")),
                ('image_data', models.BinaryField(help_text='Manufacturer logo image')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.ManyToManyField(help_text='Sections this manufacturer belongs to', related_name='manufacturers', to='products.section')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
