# Generated by Django 5.2.6 on 2025-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_section_options_remove_product_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available quantity in stock'),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('seals', 'Seals'), ('packing', 'Packing'), ('pumps', 'Pumps')], default='pumps', help_text='Which page should this section appear on', max_length=20),
        ),
    ]
