# Generated by Django 5.2.5 on 2025-09-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_migrate_material_to_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
    ]
