# Generated by Django 5.2.6 on 2025-09-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_map_sections_to_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='order',
            field=models.PositiveIntegerField(help_text='Display order in navigation (must be unique)', unique=True),
        ),
    ]
