# Generated by Django 5.2.5 on 2025-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_recreate_productimage_with_binary_storage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_image_order'),
        ),
    ]
