# Generated by Django 5.2.5 on 2025-09-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
