# Generated by Django 5.2.6 on 2025-09-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_old_gallery_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='sections',
        ),
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
