# Generated by Django 5.2.6 on 2025-09-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_gallery_product_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('description', models.CharField(blank=True, help_text='Optional description of the file', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this file is publicly accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='products.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'order'), name='unique_product_attachment_order')],
            },
        ),
    ]
