# Generated by Django 5.2.5 on 2025-09-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_make_filename_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
