# Generated by Django 5.2.6 on 2025-09-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attachment_content_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attachment_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attachment_filename',
        ),
    ]
