# Generated by Django 5.2.5 on 2025-09-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='url',
            field=models.URLField(blank=True, help_text="Manufacturer's website URL", null=True),
        ),
    ]
