# Generated by Django 5.2.5 on 2025-09-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_manufacturer_order_alter_manufacturer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description for the section', max_length=800, null=True),
        ),
    ]
