# Generated by Django 5.2.6 on 2025-09-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_section_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_data', models.BinaryField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage or featured sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
