# Generated by Django 5.2.6 on 2025-09-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_newgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order', 'created_at'], 'verbose_name_plural': 'Service & Repair Gallery'},
        ),
        migrations.AlterModelOptions(
            name='newgallery',
            options={'ordering': ['order', 'created_at'], 'verbose_name_plural': 'New Equipment Gallery'},
        ),
    ]
