# Generated by Django 5.2.6 on 2025-09-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_gallery_options_alter_newgallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='newgallery',
            name='is_featured',
        ),
    ]
