# Generated by Django 5.2.6 on 2025-09-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Pumps', 'Mechanical Seals')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'pumps', 'mechanical-seals')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Page description text')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (optional)', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (optional)', max_length=300)),
                ('active', models.BooleanField(default=True, help_text='Whether this category is active and accessible')),
                ('order', models.PositiveIntegerField(help_text='Display order in navigation (must be unique)', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for the section', max_length=800, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_category', models.ForeignKey(blank=True, help_text='Which equipment category this section belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='equipment.equipmentcategory')),
            ],
            options={
                'ordering': ['equipment_category__order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, help_text="Manufacturer's website URL", null=True)),
                ('image_data', models.BinaryField(help_text='Manufacturer logo image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.ManyToManyField(help_text='Sections this manufacturer belongs to', related_name='manufacturers', to='equipment.section')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
