# Generated by Django 5.2.5 on 2025-09-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
