# Generated by Django 5.2.5 on 2025-09-03 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline',
            field=models.CharField(max_length=300, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(max_length=254, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='hours',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='founded',
            field=models.CharField(max_length=10, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='employees',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
    ]
