# Generated by Django 5.2.6 on 2025-09-18 19:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('date', models.DateField()),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_product_views', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Average session duration in minutes')),
                ('bounce_rate', models.FloatField(default=0.0, help_text='Percentage of single-page sessions')),
                ('top_pages', models.JSONField(default=dict, help_text='Top pages with view counts')),
                ('top_products', models.JSONField(default=dict, help_text='Top products with view counts')),
                ('top_countries', models.JSONField(default=dict, help_text='Top countries with visitor counts')),
                ('top_referrers', models.JSONField(default=dict, help_text='Top referrers with counts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'date'], name='analytics_a_period_7026ca_idx')],
                'unique_together': {('period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('timezone_name', models.CharField(blank=True, max_length=100)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='analytics_v_ip_addr_d10bd1_idx'), models.Index(fields=['first_visit'], name='analytics_v_first_v_2a312f_idx'), models.Index(fields=['last_visit'], name='analytics_v_last_vi_c62641_idx')],
                'unique_together': {('ip_address',)},
            },
        ),
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('total_time_viewed', models.PositiveIntegerField(default=0, help_text='Total time in seconds')),
                ('avg_time_viewed', models.FloatField(default=0.0, help_text='Average time in seconds')),
                ('cart_additions', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Cart additions / unique views')),
                ('purchases', models.PositiveIntegerField(default=0, help_text='Actual purchases')),
                ('purchase_rate', models.FloatField(default=0.0, help_text='Purchases / unique views')),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_stats', to='products.product')),
            ],
            options={
                'ordering': ['-total_views', '-unique_views'],
                'indexes': [models.Index(fields=['total_views'], name='analytics_p_total_v_5217ea_idx'), models.Index(fields=['unique_views'], name='analytics_p_unique__3b0587_idx'), models.Index(fields=['conversion_rate'], name='analytics_p_convers_ee1562_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=50)),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('scroll', 'Scroll'), ('download', 'Download'), ('form_submit', 'Form Submit'), ('video_play', 'Video Play'), ('image_view', 'Image View'), ('contact_form', 'Contact Form'), ('quote_request', 'Quote Request'), ('phone_click', 'Phone Click'), ('email_click', 'Email Click'), ('external_link', 'External Link'), ('cart_add', 'Add to Cart'), ('cart_remove', 'Remove from Cart')], max_length=20)),
                ('element_id', models.CharField(blank=True, max_length=100)),
                ('element_class', models.CharField(blank=True, max_length=100)),
                ('element_text', models.CharField(blank=True, max_length=200)),
                ('page_path', models.CharField(max_length=500)),
                ('metadata', models.JSONField(default=dict, help_text='Additional event data')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.product')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytics_u_event_t_42317c_idx'), models.Index(fields=['visitor', 'timestamp'], name='analytics_u_visitor_851579_idx'), models.Index(fields=['product', 'timestamp'], name='analytics_u_product_25629b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=50)),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_results', models.JSONField(default=list, help_text='List of product IDs clicked from results')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='analytics.visitor')),
            ],
            options={
                'indexes': [models.Index(fields=['query'], name='analytics_s_query_44edad_idx'), models.Index(fields=['timestamp'], name='analytics_s_timesta_dab2b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=50)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('viewed_images', models.JSONField(default=list, help_text='List of image IDs viewed')),
                ('viewed_attachments', models.JSONField(default=list, help_text='List of attachment IDs viewed')),
                ('time_on_page', models.PositiveIntegerField(blank=True, help_text='Time spent viewing product in seconds', null=True)),
                ('scroll_depth', models.PositiveIntegerField(blank=True, help_text='Max scroll depth percentage', null=True)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='products.product')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='analytics.visitor')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'timestamp'], name='analytics_p_product_f14689_idx'), models.Index(fields=['visitor', 'timestamp'], name='analytics_p_visitor_704c40_idx'), models.Index(fields=['timestamp'], name='analytics_p_timesta_878d8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(max_length=500)),
                ('full_url', models.URLField(max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('load_time', models.PositiveIntegerField(blank=True, help_text='Page load time in milliseconds', null=True)),
                ('scroll_depth', models.PositiveIntegerField(blank=True, help_text='Max scroll depth percentage', null=True)),
                ('time_on_page', models.PositiveIntegerField(blank=True, help_text='Time spent on page in seconds', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor')),
            ],
            options={
                'indexes': [models.Index(fields=['visitor', 'timestamp'], name='analytics_p_visitor_143477_idx'), models.Index(fields=['path'], name='analytics_p_path_3382b5_idx'), models.Index(fields=['timestamp'], name='analytics_p_timesta_835321_idx'), models.Index(fields=['session_id'], name='analytics_p_session_a580f2_idx')],
            },
        ),
    ]
