# Generated by Django 5.2.6 on 2025-09-20 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Service & Repair', 'New Equipment')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'service-repair', 'new-equipment')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Page description text')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (optional)', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (optional)', max_length=300)),
                ('active', models.BooleanField(default=True, help_text='Whether this gallery category is active and accessible')),
                ('order', models.PositiveIntegerField(help_text='Display order in navigation (must be unique)', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_data', models.BinaryField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galleries.gallerycategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('category', 'order'), name='unique_gallery_image_order')],
            },
        ),
    ]
